# This file is auto-generated by mcp_generator.py.
# MCP server stub generated from OpenAPI spec.
import os
import json
import re
from typing import Optional, Union, Any
from dotenv import load_dotenv
load_dotenv()
from fastmcp import FastMCP
import requests
import sys
# MCP servers must only output JSON-RPC to stdout, so use stderr for logging
print("[MCP SERVER] FastMCP server running.", file=sys.stderr)
if __name__ == "__main__":
    mcp = FastMCP("my-server")

    @mcp.tool(name='adminApi_delete_app', description="delete app: Delete an app, its memberships, and stop its Telegram bot. Only the app Owner may call this. Existing sessions and messages are not cascaded.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)")
    def adminApi_delete_app(body: Optional[dict] = None):
        '''Delete an app, its memberships, and stop its Telegram bot. Only the app Owner may call this. Existing sessions and messages are not cascaded.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/adminApi/delete_app"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='adminApi_set_log_level', description="set log level: Change the server's log level at runtime (platform admin only).\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - level (integer) (required)")
    def adminApi_set_log_level(body: Optional[dict] = None):
        '''Change the server's log level at runtime (platform admin only).'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/adminApi/set_log_level"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='adminApi_get_users', description="get users: List all registered users with their platform roles (platform admin only).")
    def adminApi_get_users():
        '''List all registered users with their platform roles (platform admin only).'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/adminApi/get_users"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='adminApi_set_role', description="set role: Override a user's platform role (platform admin only).\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - role (integer) (required)\n  - userPubId (string) (required)")
    def adminApi_set_role(body: Optional[dict] = None):
        '''Override a user's platform role (platform admin only).'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/adminApi/set_role"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='adminApi_get_all_apps', description="get all apps: List all apps on the platform (platform admin only).")
    def adminApi_get_all_apps():
        '''List all apps on the platform (platform admin only).'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/adminApi/get_all_apps"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_create_app', description="create app: Register a new tenant app with its Telegram bot token. The caller becomes the app Owner and the bot is registered and started.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appName (string) (optional)\n  - messagePersistenceEnabled (boolean) (optional)\n  - tgBotToken (string) (required)")
    def appAdminApi_create_app(body: Optional[dict] = None):
        '''Register a new tenant app with its Telegram bot token. The caller becomes the app Owner and the bot is registered and started.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/create_app"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_edit_app', description="edit app: Update an app's name, Telegram bot token, active flag, or message persistence. Changing the token or active flag restarts or stops the app's bot.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - active (boolean) (optional)\n  - appName (string) (optional)\n  - appPublicId (string) (required)\n  - messagePersistenceEnabled (boolean) (optional)\n  - tgBotToken (string) (optional)")
    def appAdminApi_edit_app(body: Optional[dict] = None):
        '''Update an app's name, Telegram bot token, active flag, or message persistence. Changing the token or active flag restarts or stops the app's bot.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/edit_app"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_list_apps', description="list apps: List apps the caller is a member of. The response includes each app's Telegram bot token \u2014 treat it as a secret.")
    def appAdminApi_list_apps():
        '''List apps the caller is a member of. The response includes each app's Telegram bot token — treat it as a secret.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/list_apps"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_enable_support_user', description="enable support user: Enable an app member to receive support messages in Telegram.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)\n  - userPubId (string) (required)")
    def appAdminApi_enable_support_user(body: Optional[dict] = None):
        '''Enable an app member to receive support messages in Telegram.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/enable_support_user"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_disable_support_user', description="disable support user: Stop an app member from receiving support messages in Telegram.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)\n  - userPubId (string) (required)")
    def appAdminApi_disable_support_user(body: Optional[dict] = None):
        '''Stop an app member from receiving support messages in Telegram.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/disable_support_user"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_add_app_member', description="add app member: Add a user to an app as a Support member. Use SetAppMemberRole to change their role afterwards.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)\n  - userPubId (string) (required)")
    def appAdminApi_add_app_member(body: Optional[dict] = None):
        '''Add a user to an app as a Support member. Use SetAppMemberRole to change their role afterwards.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/add_app_member"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_set_app_member_role', description="set app member role: Change an app member's role (Owner, Admin, or Support). Only the app Owner may call this.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)\n  - role (integer) (required)\n  - userPubId (string) (required)")
    def appAdminApi_set_app_member_role(body: Optional[dict] = None):
        '''Change an app member's role (Owner, Admin, or Support). Only the app Owner may call this.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/set_app_member_role"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_list_app_members', description="list app members: List members of an app with their roles and support-enabled status.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)")
    def appAdminApi_list_app_members(body: Optional[dict] = None):
        '''List members of an app with their roles and support-enabled status.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/list_app_members"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_enable_message_persistence', description="enable message persistence: Enable disk persistence for the app's chat messages; existing in-memory messages are migrated to disk.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)")
    def appAdminApi_enable_message_persistence(body: Optional[dict] = None):
        '''Enable disk persistence for the app's chat messages; existing in-memory messages are migrated to disk.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/enable_message_persistence"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appAdminApi_disable_message_persistence', description="disable message persistence: Disable disk persistence for the app's chat messages; existing messages are migrated to the in-memory store (purged after 24h).\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)")
    def appAdminApi_disable_message_persistence(body: Optional[dict] = None):
        '''Disable disk persistence for the app's chat messages; existing messages are migrated to the in-memory store (purged after 24h).'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appAdminApi/disable_message_persistence"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appApi_create_chat_session', description="create chat session: Create a new support chat session for the given end-user of this app. Returns the 16-character session_id used by all subsequent message operations. Caller must be an App connection.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - userPubId (string) (required)")
    def appApi_create_chat_session(body: Optional[dict] = None):
        '''Create a new support chat session for the given end-user of this app. Returns the 16-character session_id used by all subsequent message operations. Caller must be an App connection.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appApi/create_chat_session"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appApi_send_message', description="send message: Send a message into an existing chat session. The message is stored and relayed to the app's support staff via Telegram. Support staff reply from Telegram, not via this endpoint.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - content (string) (required)\n  - sessionId (string) (required)")
    def appApi_send_message(body: Optional[dict] = None):
        '''Send a message into an existing chat session. The message is stored and relayed to the app's support staff via Telegram. Support staff reply from Telegram, not via this endpoint.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appApi/send_message"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appApi_list_messages', description="list messages: List all messages of a chat session, oldest first.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - sessionId (string) (required)")
    def appApi_list_messages(body: Optional[dict] = None):
        '''List all messages of a chat session, oldest first.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appApi/list_messages"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appApi_subscribe_events', description="subscribe events: Subscribe to live chat events (new messages) for a session; pass unsub: true to unsubscribe. Events are delivered as stream frames over the legacy protocol only.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - sessionId (string) (required)\n  - unsub (boolean) (optional)")
    def appApi_subscribe_events(body: Optional[dict] = None):
        '''Subscribe to live chat events (new messages) for a session; pass unsub: true to unsubscribe. Events are delivered as stream frames over the legacy protocol only.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appApi/subscribe_events"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appApi_close_chat_session', description="close chat session: Close a chat session; no further messages can be sent to it.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - sessionId (string) (required)")
    def appApi_close_chat_session(body: Optional[dict] = None):
        '''Close a chat session; no further messages can be sent to it.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appApi/close_chat_session"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appApi_list_chat_sessions', description="list chat sessions: List chat sessions visible to the caller (the app's sessions for App connections, the user's own sessions otherwise).")
    def appApi_list_chat_sessions():
        '''List chat sessions visible to the caller (the app's sessions for App connections, the user's own sessions otherwise).'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appApi/list_chat_sessions"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='appConnect_app_connect', description="app connect: Connect as an app widget on behalf of an end-user, declaring the app and user public ids. Runs at WebSocket handshake time via the Sec-WebSocket-Protocol header; not callable as a tool.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - appPublicId (string) (required)\n  - userPublicId (string) (required)")
    def appConnect_app_connect(body: Optional[dict] = None):
        '''Connect as an app widget on behalf of an end-user, declaring the app and user public ids. Runs at WebSocket handshake time via the Sec-WebSocket-Protocol header; not callable as a tool.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/appConnect/app_connect"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='authApi_init', description="init: Authenticate this connection with a honey.id access token. Runs at WebSocket handshake time via the Sec-WebSocket-Protocol header; not callable as a tool.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - accessToken (string) (required)")
    def authApi_init(body: Optional[dict] = None):
        '''Authenticate this connection with a honey.id access token. Runs at WebSocket handshake time via the Sec-WebSocket-Protocol header; not callable as a tool.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/authApi/init"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='supportApi_set_my_tg_handle', description="set my tg handle: Set the caller's Telegram handle, used to route support replies. The handle is bound to a Telegram chat when the member sends /start to the app's bot.\n\nRequest Body Schema:\nThe 'body' parameter should be a JSON object with the following structure:\n  - tgHandle (string) (required)")
    def supportApi_set_my_tg_handle(body: Optional[dict] = None):
        '''Set the caller's Telegram handle, used to route support replies. The handle is bound to a Telegram chat when the member sends /start to the app's bot.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/supportApi/set_my_tg_handle"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        json_data = body if body is not None else None
        headers['Content-Type'] = 'application/json'
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies, json=json_data)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='supportApi_get_my_tg_handle', description="get my tg handle: Get the caller's currently configured Telegram handle, if any.")
    def supportApi_get_my_tg_handle():
        '''Get the caller's currently configured Telegram handle, if any.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/supportApi/get_my_tg_handle"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    @mcp.tool(name='userApi_get_my_info', description="get my info: Return the caller's public id, username, and platform role.")
    def userApi_get_my_info():
        '''Return the caller's public id, username, and platform role.'''
        base_url = os.getenv("BASE_URL", "https://api.support.cafe")
        api_url = f"{base_url}/userApi/get_my_info"
        # Fix double slashes in URL (except after protocol)
        api_url = re.sub(r"(?<!:)/+", "/", api_url)
        params = {}
        headers = {}
        cookies = {}
        extra_headers = os.getenv('EXTRA_HEADERS')
        if extra_headers:
            try:
                for k, v in json.loads(extra_headers).items():
                    headers[k] = v
            except Exception as e:
                print('Failed to parse EXTRA_HEADERS:', e, file=sys.stderr)
        auth_satisfied = False
        auth_error_msgs = []
        if not auth_satisfied:
            try:
                token = os.getenv('HONEYIDAUTH_TOKEN')
                if not token:
                    raise ValueError('Missing Bearer token in .env: HONEYIDAUTH_TOKEN')
                headers['Authorization'] = f'Bearer {token}'
                auth_satisfied = True
            except Exception as e:
                auth_error_msgs.append(str(e))
        if not auth_satisfied:
            raise ValueError('No valid authentication found. Details: ' + '; '.join(auth_error_msgs))
        try:
            resp = requests.post(api_url, params=params, headers=headers, cookies=cookies)
            resp.raise_for_status()  # Raise an exception for bad status codes
            if 'application/json' in resp.headers.get('Content-Type', ''):
                return resp.json()
            else:
                return {'raw': resp.text, 'status_code': resp.status_code}
        except requests.exceptions.RequestException as e:
            raise ValueError(f'HTTP request failed: {str(e)}')
        except Exception as e:
            raise ValueError(f'Unexpected error: {str(e)}')

    mcp.run(transport="stdio")
